-- SEGUNDO PUNTO: 
-- LISTA DE CLIENTES, CANTIDAD DE FACTURAS Y VALOR TOTAL DE LAS MISMAS
SELECT c.CEDULA, c.NOMBRE, 
       COUNT(DISTINCT f.NO_FACTURA) AS CantidadFacturas, 
       COALESCE(SUM(p.VALOR), 0) AS TotalGastado
FROM CLIENTE c
LEFT JOIN FACTURA f ON c.CEDULA = f.CLIENTE
LEFT JOIN PRODUCTOS p ON f.PRODUCTO = p.ID
GROUP BY c.CEDULA, c.NOMBRE
ORDER BY TotalGastado DESC;

-- TERCER PUNTO:
-- PROCEDIMIENTO PARA OBTENER EL ARTÍCULO MÁS CARO COMPRADO POR UN CLIENTE
CREATE OR REPLACE FUNCTION ObtenerProductoMasCaro(_cedula VARCHAR)
RETURNS TABLE (Producto VARCHAR, Precio DECIMAL) AS $$
BEGIN
    RETURN QUERY
    SELECT p.NOMBRE, p.VALOR
    FROM FACTURA f
    INNER JOIN PRODUCTOS p ON f.PRODUCTO = p.ID
    WHERE f.CLIENTE = _cedula
    ORDER BY p.VALOR DESC
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;

-- LINEA PARA EJECUTAR Y OBTENER EL ARTÍCULO MÁS CARO COMPRADO POR UN CLIENTE
SELECT * FROM ObtenerProductoMasCaro('234567896');

-- CUARTO PUNTO:
-- LISTAR CLIENTES QUE NO HAN HECHO NINGUNA COMPRA
SELECT c.CEDULA, c.NOMBRE
FROM CLIENTE c
LEFT JOIN FACTURA f ON c.CEDULA = f.CLIENTE
WHERE f.NO_FACTURA IS NULL;

-- QUINTO PUNTO:
-- FUNCIÓN PARA EXTRAER UN VALOR DE UN TEXTO
CREATE OR REPLACE FUNCTION ObtenerCampo(_texto TEXT, _campo TEXT)
RETURNS TEXT AS $$
DECLARE
    _inicio INT;
    _fin INT;
    _resultado TEXT;
BEGIN
    _inicio := POSITION(_campo || ':' IN _texto) + LENGTH(_campo) + 1;
    IF _inicio = LENGTH(_campo) + 1 THEN
        RETURN NULL; -- Si el campo no existe
    END IF;

    _fin := POSITION('|' IN SUBSTRING(_texto FROM _inicio));
    IF _fin = 0 THEN
        _resultado := SUBSTRING(_texto FROM _inicio);
    ELSE
        _resultado := SUBSTRING(_texto FROM _inicio FOR _fin - 1);
    END IF;

    RETURN _resultado;
END;
$$ LANGUAGE plpgsql;

-- LINEA PARA EJECUTAR Y EXTRAER UN VALOR DE UN TEXTO
SELECT ObtenerCampo('aut:11111|respuesta:Ok|recibo:33333333', 'respuesta') AS Resultado;
